packages: []

catalog:
  '@eslint/js': ^9.39.2
  baseline-browser-mapping: ^2.9.19
  eslint: ^9.39.2
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-security: ^3.0.1
  eslint-plugin-sonarjs: ^3.0.7
  globals: ^16.5.0
  local-pkg: ^1.1.2

catalogs:
  dev:
    '@eslint/config-inspector': ^1.4.2
    '@frabbit/prettier-config': ^2.0.0
    '@types/node': ^24.10.13
    '@typescript/native-preview': 7.0.0-dev.20251202.1
    bumpp: ^10.4.1
    eslint-typegen: ^2.3.0
    prettier: ^3.8.1
    rolldown-plugin-require-cjs: ^0.3.3
    tsdown: ^0.17.2
    typescript: ^5.9.3
    unrun: ^0.2.27
  parsers:
    jsonc-eslint-parser: ^2.4.2
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.2
  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.6.0
    '@eslint/markdown': ^7.5.1
    '@unocss/eslint-plugin': ^66.6.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-antfu: ^3.2.1
    eslint-plugin-baseline-js: ^0.4.2
    eslint-plugin-command: ^3.4.0
    eslint-plugin-de-morgan: ^2.0.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsdoc: ^61.7.1
    eslint-plugin-jsonc: ^2.21.1
    eslint-plugin-n: ^17.23.2
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.5.0
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-sxzz: ^0.4.3
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-vue: ^10.7.0
    eslint-plugin-yml: ^1.19.1
    typescript-eslint: ^8.55.0

overrides:
  is-core-module: npm:@no-shims/is-core-module
